<?php
namespace App\Helpers;

class MoveDatabase
{
    public static function getMove($name)
    {
        return self::ALL_MOVES[$name] ?? null;
    }

    const ALL_MOVES = [
        // === NORMAL ===
        'tackle' => ['name' => 'tackle', 'name_es' => 'Placaje', 'power' => 40, 'accuracy' => 100, 'pp' => 35, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'quick-attack' => ['name' => 'quick-attack', 'name_es' => 'Ataque Rápido', 'power' => 40, 'accuracy' => 100, 'pp' => 30, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'scratch' => ['name' => 'scratch', 'name_es' => 'Arañazo', 'power' => 40, 'accuracy' => 100, 'pp' => 35, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'pound' => ['name' => 'pound', 'name_es' => 'Destructor', 'power' => 40, 'accuracy' => 100, 'pp' => 35, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'body-slam' => ['name' => 'body-slam', 'name_es' => 'Golpe Cuerpo', 'power' => 85, 'accuracy' => 100, 'pp' => 15, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => 'paralysis', 'status_chance' => 30],
        'hyper-beam' => ['name' => 'hyper-beam', 'name_es' => 'Hiperrayo', 'power' => 150, 'accuracy' => 90, 'pp' => 5, 'type' => 'normal', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'giga-impact' => ['name' => 'giga-impact', 'name_es' => 'Giga Impacto', 'power' => 150, 'accuracy' => 90, 'pp' => 5, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'facade' => ['name' => 'facade', 'name_es' => 'Fachada', 'power' => 70, 'accuracy' => 100, 'pp' => 20, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'swift' => ['name' => 'swift', 'name_es' => 'Velocidad', 'power' => 60, 'accuracy' => 100, 'pp' => 20, 'type' => 'normal', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'slash' => ['name' => 'slash', 'name_es' => 'Cuchillada', 'power' => 70, 'accuracy' => 100, 'pp' => 20, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'strength' => ['name' => 'strength', 'name_es' => 'Fuerza', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'headbutt' => ['name' => 'headbutt', 'name_es' => 'Cabezazo', 'power' => 70, 'accuracy' => 100, 'pp' => 15, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'return' => ['name' => 'return', 'name_es' => 'Retribución', 'power' => 102, 'accuracy' => 100, 'pp' => 20, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'judgment' => ['name' => 'judgment', 'name_es' => 'Sentencia', 'power' => 100, 'accuracy' => 100, 'pp' => 10, 'type' => 'normal', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'extreme-speed' => ['name' => 'extreme-speed', 'name_es' => 'Vel. Extrema', 'power' => 80, 'accuracy' => 100, 'pp' => 5, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'boomburst' => ['name' => 'boomburst', 'name_es' => 'Estallido', 'power' => 140, 'accuracy' => 100, 'pp' => 10, 'type' => 'normal', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'tri-attack' => ['name' => 'tri-attack', 'name_es' => 'Triataque', 'power' => 80, 'accuracy' => 100, 'pp' => 10, 'type' => 'normal', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'double-edge' => ['name' => 'double-edge', 'name_es' => 'Doble Filo', 'power' => 120, 'accuracy' => 100, 'pp' => 15, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'take-down' => ['name' => 'take-down', 'name_es' => 'Derribo', 'power' => 90, 'accuracy' => 85, 'pp' => 20, 'type' => 'normal', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        // === FIRE ===
        'ember' => ['name' => 'ember', 'name_es' => 'Ascuas', 'power' => 40, 'accuracy' => 100, 'pp' => 25, 'type' => 'fire', 'damage_class' => 'special', 'status_effect' => 'burn', 'status_chance' => 10],
        'flamethrower' => ['name' => 'flamethrower', 'name_es' => 'Lanzallamas', 'power' => 90, 'accuracy' => 100, 'pp' => 15, 'type' => 'fire', 'damage_class' => 'special', 'status_effect' => 'burn', 'status_chance' => 10],
        'fire-blast' => ['name' => 'fire-blast', 'name_es' => 'Llamarada', 'power' => 110, 'accuracy' => 85, 'pp' => 5, 'type' => 'fire', 'damage_class' => 'special', 'status_effect' => 'burn', 'status_chance' => 10],
        'fire-punch' => ['name' => 'fire-punch', 'name_es' => 'Puño Fuego', 'power' => 75, 'accuracy' => 100, 'pp' => 15, 'type' => 'fire', 'damage_class' => 'physical', 'status_effect' => 'burn', 'status_chance' => 10],
        'flame-charge' => ['name' => 'flame-charge', 'name_es' => 'Nitrocarga', 'power' => 50, 'accuracy' => 100, 'pp' => 20, 'type' => 'fire', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'heat-wave' => ['name' => 'heat-wave', 'name_es' => 'Onda Ígnea', 'power' => 95, 'accuracy' => 90, 'pp' => 10, 'type' => 'fire', 'damage_class' => 'special', 'status_effect' => 'burn', 'status_chance' => 10],
        'fire-fang' => ['name' => 'fire-fang', 'name_es' => 'Colmillo Ígneo', 'power' => 65, 'accuracy' => 95, 'pp' => 15, 'type' => 'fire', 'damage_class' => 'physical', 'status_effect' => 'burn', 'status_chance' => 10],
        'blaze-kick' => ['name' => 'blaze-kick', 'name_es' => 'Patada Ígnea', 'power' => 85, 'accuracy' => 90, 'pp' => 10, 'type' => 'fire', 'damage_class' => 'physical', 'status_effect' => 'burn', 'status_chance' => 10],
        'overheat' => ['name' => 'overheat', 'name_es' => 'Sofoco', 'power' => 130, 'accuracy' => 90, 'pp' => 5, 'type' => 'fire', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'sacred-fire' => ['name' => 'sacred-fire', 'name_es' => 'Fuego Sagrado', 'power' => 100, 'accuracy' => 95, 'pp' => 5, 'type' => 'fire', 'damage_class' => 'physical', 'status_effect' => 'burn', 'status_chance' => 50],
        'magma-storm' => ['name' => 'magma-storm', 'name_es' => 'Lluvia Ígnea', 'power' => 100, 'accuracy' => 75, 'pp' => 5, 'type' => 'fire', 'damage_class' => 'special', 'status_effect' => 'burn', 'status_chance' => 100],
        'flare-blitz' => ['name' => 'flare-blitz', 'name_es' => 'Envite Ígneo', 'power' => 120, 'accuracy' => 100, 'pp' => 15, 'type' => 'fire', 'damage_class' => 'physical', 'status_effect' => 'burn', 'status_chance' => 10],
        'blue-flare' => ['name' => 'blue-flare', 'name_es' => 'Llama Azul', 'power' => 130, 'accuracy' => 85, 'pp' => 5, 'type' => 'fire', 'damage_class' => 'special', 'status_effect' => 'burn', 'status_chance' => 20],
        'fusion-flare' => ['name' => 'fusion-flare', 'name_es' => 'Llama Fusión', 'power' => 100, 'accuracy' => 100, 'pp' => 5, 'type' => 'fire', 'damage_class' => 'special', 'status_effect' => 'burn', 'status_chance' => 0],
        'lava-plume' => ['name' => 'lava-plume', 'name_es' => 'Humareda', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'fire', 'damage_class' => 'special', 'status_effect' => 'burn', 'status_chance' => 30],
        'v-create' => ['name' => 'v-create', 'name_es' => 'V de Fuego', 'power' => 180, 'accuracy' => 95, 'pp' => 5, 'type' => 'fire', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'mystical-fire' => ['name' => 'mystical-fire', 'name_es' => 'Fuego Místico', 'power' => 75, 'accuracy' => 100, 'pp' => 10, 'type' => 'fire', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'will-o-wisp' => ['name' => 'will-o-wisp', 'name_es' => 'Fuego Fatuo', 'power' => 0, 'accuracy' => 85, 'pp' => 15, 'type' => 'fire', 'damage_class' => 'status', 'status_effect' => 'burn', 'status_chance' => 100],
        // === WATER ===
        'water-gun' => ['name' => 'water-gun', 'name_es' => 'Pistola Agua', 'power' => 40, 'accuracy' => 100, 'pp' => 25, 'type' => 'water', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'surf' => ['name' => 'surf', 'name_es' => 'Surf', 'power' => 90, 'accuracy' => 100, 'pp' => 15, 'type' => 'water', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'hydro-pump' => ['name' => 'hydro-pump', 'name_es' => 'Hidrobomba', 'power' => 110, 'accuracy' => 80, 'pp' => 5, 'type' => 'water', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'scald' => ['name' => 'scald', 'name_es' => 'Escaldar', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'water', 'damage_class' => 'special', 'status_effect' => 'burn', 'status_chance' => 30],
        'waterfall' => ['name' => 'waterfall', 'name_es' => 'Cascada', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'water', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'aqua-tail' => ['name' => 'aqua-tail', 'name_es' => 'Acua Cola', 'power' => 90, 'accuracy' => 90, 'pp' => 10, 'type' => 'water', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'water-pulse' => ['name' => 'water-pulse', 'name_es' => 'Hidropulso', 'power' => 60, 'accuracy' => 100, 'pp' => 20, 'type' => 'water', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'bubble-beam' => ['name' => 'bubble-beam', 'name_es' => 'Rayo Burbuja', 'power' => 65, 'accuracy' => 100, 'pp' => 20, 'type' => 'water', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'aqua-jet' => ['name' => 'aqua-jet', 'name_es' => 'Acua Jet', 'power' => 40, 'accuracy' => 100, 'pp' => 20, 'type' => 'water', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'liquidation' => ['name' => 'liquidation', 'name_es' => 'Hidroariete', 'power' => 85, 'accuracy' => 100, 'pp' => 10, 'type' => 'water', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'origin-pulse' => ['name' => 'origin-pulse', 'name_es' => 'Pulso Primig.', 'power' => 110, 'accuracy' => 85, 'pp' => 10, 'type' => 'water', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'muddy-water' => ['name' => 'muddy-water', 'name_es' => 'Agua Lodosa', 'power' => 90, 'accuracy' => 85, 'pp' => 10, 'type' => 'water', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        // === GRASS ===
        'vine-whip' => ['name' => 'vine-whip', 'name_es' => 'Látigo Cepa', 'power' => 45, 'accuracy' => 100, 'pp' => 25, 'type' => 'grass', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'razor-leaf' => ['name' => 'razor-leaf', 'name_es' => 'Hoja Afilada', 'power' => 55, 'accuracy' => 95, 'pp' => 25, 'type' => 'grass', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'energy-ball' => ['name' => 'energy-ball', 'name_es' => 'Bola Energía', 'power' => 90, 'accuracy' => 100, 'pp' => 10, 'type' => 'grass', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'giga-drain' => ['name' => 'giga-drain', 'name_es' => 'Gigadrenado', 'power' => 75, 'accuracy' => 100, 'pp' => 10, 'type' => 'grass', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'leaf-blade' => ['name' => 'leaf-blade', 'name_es' => 'Hoja Aguda', 'power' => 90, 'accuracy' => 100, 'pp' => 15, 'type' => 'grass', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'seed-bomb' => ['name' => 'seed-bomb', 'name_es' => 'Bomba Germen', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'grass', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'solar-beam' => ['name' => 'solar-beam', 'name_es' => 'Rayo Solar', 'power' => 120, 'accuracy' => 100, 'pp' => 10, 'type' => 'grass', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'leaf-storm' => ['name' => 'leaf-storm', 'name_es' => 'Tormenta Floral', 'power' => 130, 'accuracy' => 90, 'pp' => 5, 'type' => 'grass', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'wood-hammer' => ['name' => 'wood-hammer', 'name_es' => 'Mazazo', 'power' => 120, 'accuracy' => 100, 'pp' => 15, 'type' => 'grass', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'power-whip' => ['name' => 'power-whip', 'name_es' => 'Latigazo', 'power' => 120, 'accuracy' => 85, 'pp' => 10, 'type' => 'grass', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'bullet-seed' => ['name' => 'bullet-seed', 'name_es' => 'Semilladora', 'power' => 25, 'accuracy' => 100, 'pp' => 30, 'type' => 'grass', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'sleep-powder' => ['name' => 'sleep-powder', 'name_es' => 'Somnífero', 'power' => 0, 'accuracy' => 75, 'pp' => 15, 'type' => 'grass', 'damage_class' => 'status', 'status_effect' => 'sleep', 'status_chance' => 100],
        'stun-spore' => ['name' => 'stun-spore', 'name_es' => 'Paralizador', 'power' => 0, 'accuracy' => 75, 'pp' => 30, 'type' => 'grass', 'damage_class' => 'status', 'status_effect' => 'paralysis', 'status_chance' => 100],
        'poison-powder' => ['name' => 'poison-powder', 'name_es' => 'Polvo Veneno', 'power' => 0, 'accuracy' => 75, 'pp' => 35, 'type' => 'grass', 'damage_class' => 'status', 'status_effect' => 'poison', 'status_chance' => 100],
        // === ELECTRIC ===
        'thunder-shock' => ['name' => 'thunder-shock', 'name_es' => 'Impactrueno', 'power' => 40, 'accuracy' => 100, 'pp' => 30, 'type' => 'electric', 'damage_class' => 'special', 'status_effect' => 'paralysis', 'status_chance' => 10],
        'thunderbolt' => ['name' => 'thunderbolt', 'name_es' => 'Rayo', 'power' => 90, 'accuracy' => 100, 'pp' => 15, 'type' => 'electric', 'damage_class' => 'special', 'status_effect' => 'paralysis', 'status_chance' => 10],
        'thunder' => ['name' => 'thunder', 'name_es' => 'Trueno', 'power' => 110, 'accuracy' => 70, 'pp' => 10, 'type' => 'electric', 'damage_class' => 'special', 'status_effect' => 'paralysis', 'status_chance' => 30],
        'thunder-punch' => ['name' => 'thunder-punch', 'name_es' => 'Puño Trueno', 'power' => 75, 'accuracy' => 100, 'pp' => 15, 'type' => 'electric', 'damage_class' => 'physical', 'status_effect' => 'paralysis', 'status_chance' => 10],
        'volt-switch' => ['name' => 'volt-switch', 'name_es' => 'Voltiocambio', 'power' => 70, 'accuracy' => 100, 'pp' => 20, 'type' => 'electric', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'wild-charge' => ['name' => 'wild-charge', 'name_es' => 'Voltio Cruel', 'power' => 90, 'accuracy' => 100, 'pp' => 15, 'type' => 'electric', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'spark' => ['name' => 'spark', 'name_es' => 'Chispa', 'power' => 65, 'accuracy' => 100, 'pp' => 20, 'type' => 'electric', 'damage_class' => 'physical', 'status_effect' => 'paralysis', 'status_chance' => 30],
        'discharge' => ['name' => 'discharge', 'name_es' => 'Chispazo', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'electric', 'damage_class' => 'special', 'status_effect' => 'paralysis', 'status_chance' => 30],
        'bolt-strike' => ['name' => 'bolt-strike', 'name_es' => 'Ataque Fulgor', 'power' => 130, 'accuracy' => 85, 'pp' => 5, 'type' => 'electric', 'damage_class' => 'physical', 'status_effect' => 'paralysis', 'status_chance' => 20],
        'fusion-bolt' => ['name' => 'fusion-bolt', 'name_es' => 'Rayo Fusión', 'power' => 100, 'accuracy' => 100, 'pp' => 5, 'type' => 'electric', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'thunder-fang' => ['name' => 'thunder-fang', 'name_es' => 'Colm. Rayo', 'power' => 65, 'accuracy' => 95, 'pp' => 15, 'type' => 'electric', 'damage_class' => 'physical', 'status_effect' => 'paralysis', 'status_chance' => 10],
        'charge-beam' => ['name' => 'charge-beam', 'name_es' => 'Rayo Carga', 'power' => 50, 'accuracy' => 90, 'pp' => 10, 'type' => 'electric', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'zap-cannon' => ['name' => 'zap-cannon', 'name_es' => 'Electrocañón', 'power' => 120, 'accuracy' => 50, 'pp' => 5, 'type' => 'electric', 'damage_class' => 'special', 'status_effect' => 'paralysis', 'status_chance' => 100],
        'thunder-wave' => ['name' => 'thunder-wave', 'name_es' => 'Onda Trueno', 'power' => 0, 'accuracy' => 90, 'pp' => 20, 'type' => 'electric', 'damage_class' => 'status', 'status_effect' => 'paralysis', 'status_chance' => 100],
        // === ICE ===
        'ice-beam' => ['name' => 'ice-beam', 'name_es' => 'Rayo Hielo', 'power' => 90, 'accuracy' => 100, 'pp' => 10, 'type' => 'ice', 'damage_class' => 'special', 'status_effect' => 'freeze', 'status_chance' => 10],
        'blizzard' => ['name' => 'blizzard', 'name_es' => 'Ventisca', 'power' => 110, 'accuracy' => 70, 'pp' => 5, 'type' => 'ice', 'damage_class' => 'special', 'status_effect' => 'freeze', 'status_chance' => 10],
        'ice-punch' => ['name' => 'ice-punch', 'name_es' => 'Puño Hielo', 'power' => 75, 'accuracy' => 100, 'pp' => 15, 'type' => 'ice', 'damage_class' => 'physical', 'status_effect' => 'freeze', 'status_chance' => 10],
        'ice-fang' => ['name' => 'ice-fang', 'name_es' => 'Colm. Hielo', 'power' => 65, 'accuracy' => 95, 'pp' => 15, 'type' => 'ice', 'damage_class' => 'physical', 'status_effect' => 'freeze', 'status_chance' => 10],
        'avalanche' => ['name' => 'avalanche', 'name_es' => 'Alud', 'power' => 60, 'accuracy' => 100, 'pp' => 10, 'type' => 'ice', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'ice-shard' => ['name' => 'ice-shard', 'name_es' => 'Canto Helado', 'power' => 40, 'accuracy' => 100, 'pp' => 30, 'type' => 'ice', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'icy-wind' => ['name' => 'icy-wind', 'name_es' => 'Viento Hielo', 'power' => 55, 'accuracy' => 95, 'pp' => 15, 'type' => 'ice', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'freeze-dry' => ['name' => 'freeze-dry', 'name_es' => 'Liofilización', 'power' => 70, 'accuracy' => 100, 'pp' => 20, 'type' => 'ice', 'damage_class' => 'special', 'status_effect' => 'freeze', 'status_chance' => 10],
        'glaciate' => ['name' => 'glaciate', 'name_es' => 'Mundo Gélido', 'power' => 65, 'accuracy' => 95, 'pp' => 10, 'type' => 'ice', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        // === FIGHTING ===
        'karate-chop' => ['name' => 'karate-chop', 'name_es' => 'Golpe Karate', 'power' => 50, 'accuracy' => 100, 'pp' => 25, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'close-combat' => ['name' => 'close-combat', 'name_es' => 'A Bocajarro', 'power' => 120, 'accuracy' => 100, 'pp' => 5, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'brick-break' => ['name' => 'brick-break', 'name_es' => 'Demolición', 'power' => 75, 'accuracy' => 100, 'pp' => 15, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'aura-sphere' => ['name' => 'aura-sphere', 'name_es' => 'Esfera Aural', 'power' => 80, 'accuracy' => 100, 'pp' => 20, 'type' => 'fighting', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'focus-blast' => ['name' => 'focus-blast', 'name_es' => 'Onda Certera', 'power' => 120, 'accuracy' => 70, 'pp' => 5, 'type' => 'fighting', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'drain-punch' => ['name' => 'drain-punch', 'name_es' => 'Puño Drenaje', 'power' => 75, 'accuracy' => 100, 'pp' => 10, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'cross-chop' => ['name' => 'cross-chop', 'name_es' => 'Tajo Cruzado', 'power' => 100, 'accuracy' => 80, 'pp' => 5, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'force-palm' => ['name' => 'force-palm', 'name_es' => 'Palmeo', 'power' => 60, 'accuracy' => 100, 'pp' => 10, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => 'paralysis', 'status_chance' => 30],
        'superpower' => ['name' => 'superpower', 'name_es' => 'Fuerza Bruta', 'power' => 120, 'accuracy' => 100, 'pp' => 5, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'mach-punch' => ['name' => 'mach-punch', 'name_es' => 'Ultrapuño', 'power' => 40, 'accuracy' => 100, 'pp' => 30, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'sacred-sword' => ['name' => 'sacred-sword', 'name_es' => 'Espada Santa', 'power' => 90, 'accuracy' => 100, 'pp' => 15, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'rock-smash' => ['name' => 'rock-smash', 'name_es' => 'Golpe Roca', 'power' => 40, 'accuracy' => 100, 'pp' => 15, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'hammer-arm' => ['name' => 'hammer-arm', 'name_es' => 'Martillazo', 'power' => 100, 'accuracy' => 90, 'pp' => 10, 'type' => 'fighting', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        // === POISON ===
        'poison-sting' => ['name' => 'poison-sting', 'name_es' => 'Picotazo Ven.', 'power' => 15, 'accuracy' => 100, 'pp' => 35, 'type' => 'poison', 'damage_class' => 'physical', 'status_effect' => 'poison', 'status_chance' => 30],
        'sludge-bomb' => ['name' => 'sludge-bomb', 'name_es' => 'Bomba Lodo', 'power' => 90, 'accuracy' => 100, 'pp' => 10, 'type' => 'poison', 'damage_class' => 'special', 'status_effect' => 'poison', 'status_chance' => 30],
        'poison-jab' => ['name' => 'poison-jab', 'name_es' => 'Puya Nociva', 'power' => 80, 'accuracy' => 100, 'pp' => 20, 'type' => 'poison', 'damage_class' => 'physical', 'status_effect' => 'poison', 'status_chance' => 30],
        'sludge-wave' => ['name' => 'sludge-wave', 'name_es' => 'Onda Tóxica', 'power' => 95, 'accuracy' => 100, 'pp' => 10, 'type' => 'poison', 'damage_class' => 'special', 'status_effect' => 'poison', 'status_chance' => 10],
        'gunk-shot' => ['name' => 'gunk-shot', 'name_es' => 'Lanza Mugre', 'power' => 120, 'accuracy' => 80, 'pp' => 5, 'type' => 'poison', 'damage_class' => 'physical', 'status_effect' => 'poison', 'status_chance' => 30],
        'cross-poison' => ['name' => 'cross-poison', 'name_es' => 'Veneno X', 'power' => 70, 'accuracy' => 100, 'pp' => 20, 'type' => 'poison', 'damage_class' => 'physical', 'status_effect' => 'poison', 'status_chance' => 10],
        'venoshock' => ['name' => 'venoshock', 'name_es' => 'Cargatóxica', 'power' => 65, 'accuracy' => 100, 'pp' => 10, 'type' => 'poison', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'acid' => ['name' => 'acid', 'name_es' => 'Ácido', 'power' => 40, 'accuracy' => 100, 'pp' => 30, 'type' => 'poison', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'sludge' => ['name' => 'sludge', 'name_es' => 'Residuos', 'power' => 65, 'accuracy' => 100, 'pp' => 20, 'type' => 'poison', 'damage_class' => 'special', 'status_effect' => 'poison', 'status_chance' => 30],
        'toxic' => ['name' => 'toxic', 'name_es' => 'Tóxico', 'power' => 0, 'accuracy' => 90, 'pp' => 10, 'type' => 'poison', 'damage_class' => 'status', 'status_effect' => 'badly_poison', 'status_chance' => 100],
        // === GROUND ===
        'mud-slap' => ['name' => 'mud-slap', 'name_es' => 'Bofetón Lodo', 'power' => 20, 'accuracy' => 100, 'pp' => 10, 'type' => 'ground', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'earthquake' => ['name' => 'earthquake', 'name_es' => 'Terremoto', 'power' => 100, 'accuracy' => 100, 'pp' => 10, 'type' => 'ground', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'earth-power' => ['name' => 'earth-power', 'name_es' => 'Poder Terrestre', 'power' => 90, 'accuracy' => 100, 'pp' => 10, 'type' => 'ground', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'drill-run' => ['name' => 'drill-run', 'name_es' => 'Taladradora', 'power' => 80, 'accuracy' => 95, 'pp' => 10, 'type' => 'ground', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'dig' => ['name' => 'dig', 'name_es' => 'Excavar', 'power' => 80, 'accuracy' => 100, 'pp' => 10, 'type' => 'ground', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'bulldoze' => ['name' => 'bulldoze', 'name_es' => 'Terratemblor', 'power' => 60, 'accuracy' => 100, 'pp' => 20, 'type' => 'ground', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'mud-shot' => ['name' => 'mud-shot', 'name_es' => 'Disparo Lodo', 'power' => 55, 'accuracy' => 95, 'pp' => 15, 'type' => 'ground', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'precipice-blades' => ['name' => 'precipice-blades', 'name_es' => 'Filo del Abismo', 'power' => 120, 'accuracy' => 85, 'pp' => 10, 'type' => 'ground', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'high-horsepower' => ['name' => 'high-horsepower', 'name_es' => 'Potencia Bruta', 'power' => 95, 'accuracy' => 95, 'pp' => 10, 'type' => 'ground', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        // === FLYING ===
        'gust' => ['name' => 'gust', 'name_es' => 'Tornado', 'power' => 40, 'accuracy' => 100, 'pp' => 35, 'type' => 'flying', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'peck' => ['name' => 'peck', 'name_es' => 'Picotazo', 'power' => 35, 'accuracy' => 100, 'pp' => 35, 'type' => 'flying', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'wing-attack' => ['name' => 'wing-attack', 'name_es' => 'Ataque Ala', 'power' => 60, 'accuracy' => 100, 'pp' => 35, 'type' => 'flying', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'air-slash' => ['name' => 'air-slash', 'name_es' => 'Tajo Aéreo', 'power' => 75, 'accuracy' => 95, 'pp' => 15, 'type' => 'flying', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'brave-bird' => ['name' => 'brave-bird', 'name_es' => 'Pájaro Osado', 'power' => 120, 'accuracy' => 100, 'pp' => 15, 'type' => 'flying', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'hurricane' => ['name' => 'hurricane', 'name_es' => 'Vendaval', 'power' => 110, 'accuracy' => 70, 'pp' => 10, 'type' => 'flying', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'aerial-ace' => ['name' => 'aerial-ace', 'name_es' => 'As Aéreo', 'power' => 60, 'accuracy' => 100, 'pp' => 20, 'type' => 'flying', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'fly' => ['name' => 'fly', 'name_es' => 'Vuelo', 'power' => 90, 'accuracy' => 95, 'pp' => 15, 'type' => 'flying', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'acrobatics' => ['name' => 'acrobatics', 'name_es' => 'Acróbata', 'power' => 55, 'accuracy' => 100, 'pp' => 15, 'type' => 'flying', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'drill-peck' => ['name' => 'drill-peck', 'name_es' => 'Pico Taladro', 'power' => 80, 'accuracy' => 100, 'pp' => 20, 'type' => 'flying', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'sky-attack' => ['name' => 'sky-attack', 'name_es' => 'Ataque Aéreo', 'power' => 140, 'accuracy' => 90, 'pp' => 5, 'type' => 'flying', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'aeroblast' => ['name' => 'aeroblast', 'name_es' => 'Aerochorro', 'power' => 100, 'accuracy' => 95, 'pp' => 5, 'type' => 'flying', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'dragon-ascent' => ['name' => 'dragon-ascent', 'name_es' => 'Ascenso Draco', 'power' => 120, 'accuracy' => 100, 'pp' => 5, 'type' => 'flying', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'oblivion-wing' => ['name' => 'oblivion-wing', 'name_es' => 'Ala Mortífera', 'power' => 80, 'accuracy' => 100, 'pp' => 10, 'type' => 'flying', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'roost' => ['name' => 'roost', 'name_es' => 'Respiro', 'power' => 0, 'accuracy' => 100, 'pp' => 10, 'type' => 'flying', 'damage_class' => 'status', 'status_effect' => 'heal', 'status_chance' => 100],
        // === PSYCHIC ===
        'confusion' => ['name' => 'confusion', 'name_es' => 'Confusión', 'power' => 50, 'accuracy' => 100, 'pp' => 25, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'psychic' => ['name' => 'psychic', 'name_es' => 'Psíquico', 'power' => 90, 'accuracy' => 100, 'pp' => 10, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'psyshock' => ['name' => 'psyshock', 'name_es' => 'Psicocarga', 'power' => 80, 'accuracy' => 100, 'pp' => 10, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'zen-headbutt' => ['name' => 'zen-headbutt', 'name_es' => 'Cabezazo Zen', 'power' => 80, 'accuracy' => 90, 'pp' => 15, 'type' => 'psychic', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'extrasensory' => ['name' => 'extrasensory', 'name_es' => 'Extrasensorial', 'power' => 80, 'accuracy' => 100, 'pp' => 20, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'future-sight' => ['name' => 'future-sight', 'name_es' => 'Premonición', 'power' => 120, 'accuracy' => 100, 'pp' => 10, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'psystrike' => ['name' => 'psystrike', 'name_es' => 'Onda Mental', 'power' => 100, 'accuracy' => 100, 'pp' => 10, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'psybeam' => ['name' => 'psybeam', 'name_es' => 'Psicorrayo', 'power' => 65, 'accuracy' => 100, 'pp' => 20, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'psycho-boost' => ['name' => 'psycho-boost', 'name_es' => 'Psicoataque', 'power' => 140, 'accuracy' => 90, 'pp' => 5, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'psycho-cut' => ['name' => 'psycho-cut', 'name_es' => 'Psicocorte', 'power' => 70, 'accuracy' => 100, 'pp' => 20, 'type' => 'psychic', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'luster-purge' => ['name' => 'luster-purge', 'name_es' => 'Resplandor', 'power' => 70, 'accuracy' => 100, 'pp' => 5, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'mist-ball' => ['name' => 'mist-ball', 'name_es' => 'Bola Neblina', 'power' => 70, 'accuracy' => 100, 'pp' => 5, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'photon-geyser' => ['name' => 'photon-geyser', 'name_es' => 'Géiser Fotónico', 'power' => 100, 'accuracy' => 100, 'pp' => 5, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'expanding-force' => ['name' => 'expanding-force', 'name_es' => 'Fuerza Expansiva', 'power' => 80, 'accuracy' => 100, 'pp' => 10, 'type' => 'psychic', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'hypnosis' => ['name' => 'hypnosis', 'name_es' => 'Hipnosis', 'power' => 0, 'accuracy' => 60, 'pp' => 20, 'type' => 'psychic', 'damage_class' => 'status', 'status_effect' => 'sleep', 'status_chance' => 100],
        // === BUG ===
        'bug-bite' => ['name' => 'bug-bite', 'name_es' => 'Picadura', 'power' => 60, 'accuracy' => 100, 'pp' => 20, 'type' => 'bug', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'x-scissor' => ['name' => 'x-scissor', 'name_es' => 'Tijera X', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'bug', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'bug-buzz' => ['name' => 'bug-buzz', 'name_es' => 'Zumbido', 'power' => 90, 'accuracy' => 100, 'pp' => 10, 'type' => 'bug', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'megahorn' => ['name' => 'megahorn', 'name_es' => 'Megacuerno', 'power' => 120, 'accuracy' => 85, 'pp' => 10, 'type' => 'bug', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'signal-beam' => ['name' => 'signal-beam', 'name_es' => 'Rayo Señal', 'power' => 75, 'accuracy' => 100, 'pp' => 15, 'type' => 'bug', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'u-turn' => ['name' => 'u-turn', 'name_es' => 'Ida y Vuelta', 'power' => 70, 'accuracy' => 100, 'pp' => 20, 'type' => 'bug', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'leech-life' => ['name' => 'leech-life', 'name_es' => 'Chupavidas', 'power' => 80, 'accuracy' => 100, 'pp' => 10, 'type' => 'bug', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'first-impression' => ['name' => 'first-impression', 'name_es' => 'Escaramuza', 'power' => 90, 'accuracy' => 100, 'pp' => 10, 'type' => 'bug', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'lunge' => ['name' => 'lunge', 'name_es' => 'Plancha', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'bug', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'pollen-puff' => ['name' => 'pollen-puff', 'name_es' => 'Bola de Polen', 'power' => 90, 'accuracy' => 100, 'pp' => 15, 'type' => 'bug', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        // === ROCK ===
        'rock-throw' => ['name' => 'rock-throw', 'name_es' => 'Lanzarrocas', 'power' => 50, 'accuracy' => 90, 'pp' => 15, 'type' => 'rock', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'stone-edge' => ['name' => 'stone-edge', 'name_es' => 'Roca Afilada', 'power' => 100, 'accuracy' => 80, 'pp' => 5, 'type' => 'rock', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'rock-slide' => ['name' => 'rock-slide', 'name_es' => 'Avalancha', 'power' => 75, 'accuracy' => 90, 'pp' => 10, 'type' => 'rock', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'power-gem' => ['name' => 'power-gem', 'name_es' => 'Joya de Luz', 'power' => 80, 'accuracy' => 100, 'pp' => 20, 'type' => 'rock', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'rock-blast' => ['name' => 'rock-blast', 'name_es' => 'Pedrada', 'power' => 25, 'accuracy' => 90, 'pp' => 10, 'type' => 'rock', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'ancient-power' => ['name' => 'ancient-power', 'name_es' => 'Poder Pasado', 'power' => 60, 'accuracy' => 100, 'pp' => 5, 'type' => 'rock', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'smack-down' => ['name' => 'smack-down', 'name_es' => 'Antiaéreo', 'power' => 50, 'accuracy' => 100, 'pp' => 15, 'type' => 'rock', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'rock-tomb' => ['name' => 'rock-tomb', 'name_es' => 'Tumba Rocas', 'power' => 60, 'accuracy' => 95, 'pp' => 15, 'type' => 'rock', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'head-smash' => ['name' => 'head-smash', 'name_es' => 'Testarazo', 'power' => 150, 'accuracy' => 80, 'pp' => 5, 'type' => 'rock', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'diamond-storm' => ['name' => 'diamond-storm', 'name_es' => 'Torm. Diamantes', 'power' => 100, 'accuracy' => 95, 'pp' => 5, 'type' => 'rock', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        // === GHOST ===
        'lick' => ['name' => 'lick', 'name_es' => 'Lengüetazo', 'power' => 30, 'accuracy' => 100, 'pp' => 30, 'type' => 'ghost', 'damage_class' => 'physical', 'status_effect' => 'paralysis', 'status_chance' => 30],
        'shadow-ball' => ['name' => 'shadow-ball', 'name_es' => 'Bola Sombra', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'ghost', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'shadow-claw' => ['name' => 'shadow-claw', 'name_es' => 'Garra Umbría', 'power' => 70, 'accuracy' => 100, 'pp' => 15, 'type' => 'ghost', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'phantom-force' => ['name' => 'phantom-force', 'name_es' => 'Golpe Fantasma', 'power' => 90, 'accuracy' => 100, 'pp' => 10, 'type' => 'ghost', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'hex' => ['name' => 'hex', 'name_es' => 'Infortunio', 'power' => 65, 'accuracy' => 100, 'pp' => 10, 'type' => 'ghost', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'shadow-punch' => ['name' => 'shadow-punch', 'name_es' => 'Puño Sombra', 'power' => 60, 'accuracy' => 100, 'pp' => 20, 'type' => 'ghost', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'shadow-sneak' => ['name' => 'shadow-sneak', 'name_es' => 'Sombra Vil', 'power' => 40, 'accuracy' => 100, 'pp' => 30, 'type' => 'ghost', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'shadow-force' => ['name' => 'shadow-force', 'name_es' => 'Golpe Umbrío', 'power' => 120, 'accuracy' => 100, 'pp' => 5, 'type' => 'ghost', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'moongeist-beam' => ['name' => 'moongeist-beam', 'name_es' => 'Rayo Umbrío', 'power' => 100, 'accuracy' => 100, 'pp' => 5, 'type' => 'ghost', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'spectral-thief' => ['name' => 'spectral-thief', 'name_es' => 'Robasombra', 'power' => 90, 'accuracy' => 100, 'pp' => 10, 'type' => 'ghost', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'poltergeist' => ['name' => 'poltergeist', 'name_es' => 'Poltergeist', 'power' => 110, 'accuracy' => 90, 'pp' => 5, 'type' => 'ghost', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        // === DRAGON ===
        'dragon-breath' => ['name' => 'dragon-breath', 'name_es' => 'Dragoaliento', 'power' => 60, 'accuracy' => 100, 'pp' => 20, 'type' => 'dragon', 'damage_class' => 'special', 'status_effect' => 'paralysis', 'status_chance' => 30],
        'dragon-claw' => ['name' => 'dragon-claw', 'name_es' => 'Garra Dragón', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'dragon', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'dragon-pulse' => ['name' => 'dragon-pulse', 'name_es' => 'Pulso Dragón', 'power' => 85, 'accuracy' => 100, 'pp' => 10, 'type' => 'dragon', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'draco-meteor' => ['name' => 'draco-meteor', 'name_es' => 'Cometa Draco', 'power' => 130, 'accuracy' => 90, 'pp' => 5, 'type' => 'dragon', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'outrage' => ['name' => 'outrage', 'name_es' => 'Enfado', 'power' => 120, 'accuracy' => 100, 'pp' => 10, 'type' => 'dragon', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'dragon-rush' => ['name' => 'dragon-rush', 'name_es' => 'Carga Dragón', 'power' => 100, 'accuracy' => 75, 'pp' => 10, 'type' => 'dragon', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'dragon-tail' => ['name' => 'dragon-tail', 'name_es' => 'Cola Dragón', 'power' => 60, 'accuracy' => 90, 'pp' => 10, 'type' => 'dragon', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'twister' => ['name' => 'twister', 'name_es' => 'Ciclón', 'power' => 40, 'accuracy' => 100, 'pp' => 20, 'type' => 'dragon', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'spacial-rend' => ['name' => 'spacial-rend', 'name_es' => 'Corte Vacío', 'power' => 100, 'accuracy' => 95, 'pp' => 5, 'type' => 'dragon', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'roar-of-time' => ['name' => 'roar-of-time', 'name_es' => 'Distorsión', 'power' => 150, 'accuracy' => 90, 'pp' => 5, 'type' => 'dragon', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'dual-chop' => ['name' => 'dual-chop', 'name_es' => 'Doble Tajo', 'power' => 40, 'accuracy' => 90, 'pp' => 15, 'type' => 'dragon', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'core-enforcer' => ['name' => 'core-enforcer', 'name_es' => 'Núcleo Castigo', 'power' => 100, 'accuracy' => 100, 'pp' => 10, 'type' => 'dragon', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        // === DARK ===
        'bite' => ['name' => 'bite', 'name_es' => 'Mordisco', 'power' => 60, 'accuracy' => 100, 'pp' => 25, 'type' => 'dark', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'crunch' => ['name' => 'crunch', 'name_es' => 'Triturar', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'dark', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'dark-pulse' => ['name' => 'dark-pulse', 'name_es' => 'Pulso Umbrío', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'dark', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'dark-void' => ['name' => 'dark-void', 'name_es' => 'Brecha Negra', 'power' => 0, 'accuracy' => 80, 'pp' => 10, 'type' => 'dark', 'damage_class' => 'status', 'status_effect' => 'sleep', 'status_chance' => 100],
        'night-slash' => ['name' => 'night-slash', 'name_es' => 'Tajo Umbrío', 'power' => 70, 'accuracy' => 100, 'pp' => 15, 'type' => 'dark', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'sucker-punch' => ['name' => 'sucker-punch', 'name_es' => 'Golpe Bajo', 'power' => 70, 'accuracy' => 100, 'pp' => 5, 'type' => 'dark', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'foul-play' => ['name' => 'foul-play', 'name_es' => 'Juego Sucio', 'power' => 95, 'accuracy' => 100, 'pp' => 15, 'type' => 'dark', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'knock-off' => ['name' => 'knock-off', 'name_es' => 'Desarme', 'power' => 65, 'accuracy' => 100, 'pp' => 20, 'type' => 'dark', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'payback' => ['name' => 'payback', 'name_es' => 'Vendetta', 'power' => 50, 'accuracy' => 100, 'pp' => 10, 'type' => 'dark', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'snarl' => ['name' => 'snarl', 'name_es' => 'Alarido', 'power' => 55, 'accuracy' => 95, 'pp' => 15, 'type' => 'dark', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'throat-chop' => ['name' => 'throat-chop', 'name_es' => 'Golpe Mordaza', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'dark', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'brutal-swing' => ['name' => 'brutal-swing', 'name_es' => 'Giro Vil', 'power' => 60, 'accuracy' => 100, 'pp' => 20, 'type' => 'dark', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        // === STEEL ===
        'metal-claw' => ['name' => 'metal-claw', 'name_es' => 'Garra Metal', 'power' => 50, 'accuracy' => 95, 'pp' => 35, 'type' => 'steel', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'iron-head' => ['name' => 'iron-head', 'name_es' => 'Cabeza Hierro', 'power' => 80, 'accuracy' => 100, 'pp' => 15, 'type' => 'steel', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'flash-cannon' => ['name' => 'flash-cannon', 'name_es' => 'Foco Resplandor', 'power' => 80, 'accuracy' => 100, 'pp' => 10, 'type' => 'steel', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'steel-wing' => ['name' => 'steel-wing', 'name_es' => 'Ala de Acero', 'power' => 70, 'accuracy' => 90, 'pp' => 25, 'type' => 'steel', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'iron-tail' => ['name' => 'iron-tail', 'name_es' => 'Cola Férrea', 'power' => 100, 'accuracy' => 75, 'pp' => 15, 'type' => 'steel', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'bullet-punch' => ['name' => 'bullet-punch', 'name_es' => 'Puño Bala', 'power' => 40, 'accuracy' => 100, 'pp' => 30, 'type' => 'steel', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'gyro-ball' => ['name' => 'gyro-ball', 'name_es' => 'Giro Bola', 'power' => 80, 'accuracy' => 100, 'pp' => 5, 'type' => 'steel', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'meteor-mash' => ['name' => 'meteor-mash', 'name_es' => 'Puño Meteoro', 'power' => 90, 'accuracy' => 90, 'pp' => 10, 'type' => 'steel', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'heavy-slam' => ['name' => 'heavy-slam', 'name_es' => 'Cuerpo Pesado', 'power' => 80, 'accuracy' => 100, 'pp' => 10, 'type' => 'steel', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'sunsteel-strike' => ['name' => 'sunsteel-strike', 'name_es' => 'Meteoimpacto', 'power' => 100, 'accuracy' => 100, 'pp' => 5, 'type' => 'steel', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'smart-strike' => ['name' => 'smart-strike', 'name_es' => 'Cabezazo', 'power' => 70, 'accuracy' => 100, 'pp' => 10, 'type' => 'steel', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'doom-desire' => ['name' => 'doom-desire', 'name_es' => 'Deseo Oculto', 'power' => 140, 'accuracy' => 100, 'pp' => 5, 'type' => 'steel', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        // === FAIRY ===
        'fairy-wind' => ['name' => 'fairy-wind', 'name_es' => 'Viento Feérico', 'power' => 40, 'accuracy' => 100, 'pp' => 30, 'type' => 'fairy', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'moonblast' => ['name' => 'moonblast', 'name_es' => 'Fuerza Lunar', 'power' => 95, 'accuracy' => 100, 'pp' => 15, 'type' => 'fairy', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'dazzling-gleam' => ['name' => 'dazzling-gleam', 'name_es' => 'Brillo Mágico', 'power' => 80, 'accuracy' => 100, 'pp' => 10, 'type' => 'fairy', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'play-rough' => ['name' => 'play-rough', 'name_es' => 'Carantoña', 'power' => 90, 'accuracy' => 90, 'pp' => 10, 'type' => 'fairy', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'draining-kiss' => ['name' => 'draining-kiss', 'name_es' => 'Beso Drenaje', 'power' => 50, 'accuracy' => 100, 'pp' => 10, 'type' => 'fairy', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'disarming-voice' => ['name' => 'disarming-voice', 'name_es' => 'Voz Cautivadora', 'power' => 40, 'accuracy' => 100, 'pp' => 15, 'type' => 'fairy', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
        'spirit-break' => ['name' => 'spirit-break', 'name_es' => 'Choque Anímico', 'power' => 75, 'accuracy' => 100, 'pp' => 15, 'type' => 'fairy', 'damage_class' => 'physical', 'status_effect' => null, 'status_chance' => 0],
        'fleur-cannon' => ['name' => 'fleur-cannon', 'name_es' => 'Cañón Floral', 'power' => 130, 'accuracy' => 90, 'pp' => 5, 'type' => 'fairy', 'damage_class' => 'special', 'status_effect' => null, 'status_chance' => 0],
    ];
}